### ISSUE TITLE
Error on starting the extension 

### ISSUE THREAD

**Issue by vpokhodnia** [jdi-testing/jdi-flash-pages#1]
Hello,

I installed the extension by downloading it, unpacking to 'C:\temp\jdi-flash-pages-master', then 'Load Unpacked' under Google Chrome Extensions (developer mode = On).

On attempt to run it, extension shows "It may have been moved or deleted" error:

<img width="689" alt="jdi_page_object_extension_error" src="https://user-images.githubusercontent.com/41125309/42590523-0dc7776e-8512-11e8-99e7-68059a61ea7e.png">

Chrome version is 67.0.3396.99 (Official Build) (64-bit). 
OS: Windows 10.

Please advise what may be causing the problem.

Thanks,
Vladimir

**Comment by RomanIovlev** [comment]
Fixed
